import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from groq import Groq

st.set_page_config(
    page_title="Solar Plant Anomaly Detection",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Sidebar ───────────────────────────────────────────────────────────────────
with st.sidebar:
    st.title("Solar Plant Anomaly Detection")
    st.divider()
    st.markdown(
        """
**Dataset**
2 solar plants | 44 inverters | 34 days
May 15 – June 17, 2020 | 15-min intervals
136,472 readings after merge
"""
    )
    st.divider()
    st.markdown(
        """
**Pipeline**

1. Load & clean — datetime parsing, merge
2. EDA — daily output, peak hours, underperformers
3. Anomaly detection — rolling z-score (window=3, shift=1)
4. Health scoring — weighted composite score
5. AI agent — Groq LLM recommendations
"""
    )
    with st.expander("Dataset Column Reference"):
        st.markdown(
            """
**Identity columns**
- DATE_TIME — timestamp of each reading, every 15 minutes
- PLANT_ID — which of the two solar plants this row belongs to
- INVERTER_KEY — unique ID for a specific inverter, each connected to a group of solar panels
- WEATHER_KEY — ID of the weather sensor at that plant. One sensor per plant, shared by all inverters.

**Power columns**
- DC_POWER — raw electricity generated by solar panels in direct current
- AC_POWER — electricity after inverter converts DC to AC for the grid. Always slightly less than DC due to conversion losses.
- DAILY_YIELD — cumulative AC energy produced since midnight, resets daily
- TOTAL_YIELD — lifetime cumulative energy since installation, always increasing

**Weather columns**
- AMBIENT_TEMPERATURE — air temperature around the panels in Celsius
- MODULE_TEMPERATURE — surface temperature of the panel itself. Higher than ambient; very high temperatures reduce efficiency.
- IRRADIATION — solar energy hitting panels per unit area (W/m²). The most important feature — no sun, no power.

*Key relationship: IRRADIATION drives DC_POWER, and the inverter converts DC_POWER to AC_POWER. High irradiation but low AC power means something is wrong with that inverter.*
"""
        )
    st.divider()
    st.markdown(
        """
*Built on a similar dataset to my Avathon technical \
interview. Fixed datetime handling and multi-index \
groupby, then built a full industrial AI pipeline.*
"""
    )

# ── File paths ────────────────────────────────────────────────────────────────
PLANT1_GEN = "/Users/vriddhi/Desktop/Plant_1_Generation_Data.csv"
PLANT2_GEN = "/Users/vriddhi/Desktop/Plant_2_Generation_Data.csv"
PLANT1_WX  = "/Users/vriddhi/Desktop/Plant_1_Weather_Sensor_Data.csv"
PLANT2_WX  = "/Users/vriddhi/Desktop/Plant_2_Weather_Sensor_Data.csv"


# ── Data loading ──────────────────────────────────────────────────────────────
@st.cache_data
def load_and_merge() -> pd.DataFrame:
    gen1 = pd.read_csv(PLANT1_GEN)
    gen2 = pd.read_csv(PLANT2_GEN)
    wx1  = pd.read_csv(PLANT1_WX)
    wx2  = pd.read_csv(PLANT2_WX)

    # Parse datetimes
    gen1["DATE_TIME"] = pd.to_datetime(gen1["DATE_TIME"], format="%d-%m-%Y %H:%M")
    gen2["DATE_TIME"] = pd.to_datetime(gen2["DATE_TIME"])
    wx1["DATE_TIME"]  = pd.to_datetime(wx1["DATE_TIME"])
    wx2["DATE_TIME"]  = pd.to_datetime(wx2["DATE_TIME"])

    # Merge generation with weather; SOURCE_KEY differs between the two tables
    m1 = pd.merge(
        gen1, wx1, on=["DATE_TIME", "PLANT_ID"], how="left",
        suffixes=("_inv", "_wx"),
    )
    m2 = pd.merge(
        gen2, wx2, on=["DATE_TIME", "PLANT_ID"], how="left",
        suffixes=("_inv", "_wx"),
    )
    df = pd.concat([m1, m2], ignore_index=True)

    df.rename(
        columns={"SOURCE_KEY_inv": "INVERTER_KEY", "SOURCE_KEY_wx": "WEATHER_KEY"},
        inplace=True,
    )

    df = df[[
        "DATE_TIME", "PLANT_ID", "INVERTER_KEY", "DC_POWER", "AC_POWER",
        "DAILY_YIELD", "TOTAL_YIELD", "WEATHER_KEY",
        "AMBIENT_TEMPERATURE", "MODULE_TEMPERATURE", "IRRADIATION",
    ]]

    df["day"]  = df["DATE_TIME"].dt.date
    df["hour"] = df["DATE_TIME"].dt.hour
    return df


# ── Analysis pipeline ─────────────────────────────────────────────────────────
@st.cache_data
def run_analysis(df: pd.DataFrame):
    # 1. Daily AC power per inverter
    daily_ac = (
        df.groupby(["day", "INVERTER_KEY"])["AC_POWER"]
        .sum()
        .reset_index()
        .rename(columns={"AC_POWER": "total_ac_power"})
    )

    # 2. Fleet average per day
    fleet_avg = (
        daily_ac.groupby("day")["total_ac_power"]
        .mean()
        .reset_index()
        .rename(columns={"total_ac_power": "fleet_avg_power"})
    )

    # 3. Merge fleet average; compute pct_deviation
    daily_ac = daily_ac.merge(fleet_avg, on="day")
    daily_ac["pct_deviation"] = (
        (daily_ac["total_ac_power"] - daily_ac["fleet_avg_power"])
        / daily_ac["fleet_avg_power"]
        * 100
    )

    # 4. Peak hours
    peak_hours = (
        df.groupby("hour")["AC_POWER"]
        .mean()
        .reset_index()
        .rename(columns={"AC_POWER": "avg_ac_power"})
    )

    # 5. Underperformer detection (avg pct_deviation per inverter, sorted asc)
    inverter_performance = (
        daily_ac.groupby("INVERTER_KEY")["pct_deviation"]
        .mean()
        .reset_index()
        .rename(columns={"pct_deviation": "avg_pct_deviation"})
    )
    inverter_performance.sort_values("avg_pct_deviation", ascending=True, inplace=True)

    # 6. Anomaly detection with rolling z-score
    daily_ac_sorted = daily_ac.sort_values(["INVERTER_KEY", "day"]).copy()

    daily_ac_sorted["rolling_mean"] = daily_ac_sorted.groupby("INVERTER_KEY")[
        "total_ac_power"
    ].transform(lambda x: x.rolling(window=3, min_periods=1).mean().shift(1))

    daily_ac_sorted["rolling_std"] = daily_ac_sorted.groupby("INVERTER_KEY")[
        "total_ac_power"
    ].transform(lambda x: x.rolling(window=3, min_periods=1).std().shift(1))

    daily_ac_sorted["z_score"] = (
        (daily_ac_sorted["total_ac_power"] - daily_ac_sorted["rolling_mean"])
        / daily_ac_sorted["rolling_std"]
    )
    daily_ac_sorted["is_anomaly"] = daily_ac_sorted["z_score"].abs() > 2

    # 7. Anomalies by inverter
    anomalies_by_inverter = (
        daily_ac_sorted[daily_ac_sorted["is_anomaly"]]
        .groupby("INVERTER_KEY")["is_anomaly"]
        .count()
        .reset_index()
        .rename(columns={"is_anomaly": "anomaly_count"})
        .sort_values("anomaly_count", ascending=False)
        .reset_index(drop=True)
    )

    # 8. Anomalies by day
    anomalies_by_day = (
        daily_ac_sorted[daily_ac_sorted["is_anomaly"]]
        .groupby("day")["is_anomaly"]
        .count()
        .reset_index()
        .rename(columns={"is_anomaly": "anomaly_count"})
        .sort_values("anomaly_count", ascending=False)
        .reset_index(drop=True)
    )

    # 9. Device health scorecard
    scorecard = anomalies_by_inverter.merge(inverter_performance, on="INVERTER_KEY", how="outer")
    scorecard["anomaly_count"] = scorecard["anomaly_count"].fillna(0)

    worst_z = (
        daily_ac_sorted.groupby("INVERTER_KEY")["z_score"]
        .agg(lambda x: x.abs().max())
        .reset_index()
        .rename(columns={"z_score": "worst_z_score"})
    )
    scorecard = scorecard.merge(worst_z, on="INVERTER_KEY", how="left")

    def normalize(s: pd.Series) -> pd.Series:
        lo, hi = s.min(), s.max()
        if hi == lo:
            return pd.Series(np.zeros(len(s)), index=s.index)
        return (s - lo) / (hi - lo)

    scorecard["anomaly_count_normalized"]     = normalize(scorecard["anomaly_count"])
    # Higher (more negative) deviation = worse, so flip after normalising
    scorecard["avg_pct_deviation_normalized"] = 1 - normalize(scorecard["avg_pct_deviation"])
    scorecard["worst_z_score_normalized"]     = normalize(scorecard["worst_z_score"])

    scorecard["health_score"] = (
        0.35 * scorecard["anomaly_count_normalized"]
        + 0.25 * scorecard["avg_pct_deviation_normalized"]
        + 0.40 * scorecard["worst_z_score_normalized"]
    )

    scorecard["health_label"] = scorecard["health_score"].apply(
        lambda s: "Critical" if s >= 0.5 else "Warning" if s >= 0.35 else "Healthy"
    )

    scorecard = (
        scorecard[[
            "INVERTER_KEY", "anomaly_count", "avg_pct_deviation",
            "worst_z_score", "health_score", "health_label",
        ]]
        .sort_values("health_score", ascending=False)
        .reset_index(drop=True)
    )

    return (
        daily_ac_sorted, fleet_avg, peak_hours,
        inverter_performance, anomalies_by_inverter,
        anomalies_by_day, scorecard,
    )


# ── Groq agentic layer ────────────────────────────────────────────────────────
def get_groq_recommendations(critical_df: pd.DataFrame) -> dict[str, str]:
    client = Groq(api_key=st.secrets["GROQ_API_KEY"])
    recommendations: dict[str, str] = {}

    for _, row in critical_df.iterrows():
        inv_id = row["INVERTER_KEY"]
        prompt = (
            "You are an industrial AI assistant for a solar plant operator. "
            "Given these Critical inverters with their anomaly count, avg deviation, "
            "worst z-score and health score, generate a 2-3 sentence plain English "
            "maintenance recommendation for each.\n\n"
            f"Inverter: {inv_id}\n"
            f"- Anomaly Count: {int(row['anomaly_count'])}\n"
            f"- Avg % Deviation from Fleet: {row['avg_pct_deviation']:.2f}%\n"
            f"- Worst Z-Score: {row['worst_z_score']:.2f}\n"
            f"- Health Score: {row['health_score']:.3f}\n"
        )
        resp = client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[{"role": "user", "content": prompt}],
        )
        recommendations[inv_id] = resp.choices[0].message.content

    return recommendations


# ── Main layout ───────────────────────────────────────────────────────────────
st.markdown("""
<style>
    .stTabs [data-baseweb="tab-list"] { gap: 8px; }
    .stTabs [data-baseweb="tab"] {
        font-size: 15px;
        font-weight: 600;
        padding: 10px 24px;
        background-color: #1e1e1e;
        border-radius: 6px 6px 0 0;
    }
    .stTabs [aria-selected="true"] {
        background-color: #2563EB;
        color: white;
    }
    .metric-card {
        background: #1e1e1e;
        border-radius: 8px;
        padding: 16px 20px;
        border-left: 4px solid #2563EB;
    }
    .section-caption {
        color: #9ca3af;
        font-size: 13px;
        margin-top: -8px;
        margin-bottom: 16px;
    }
    .rec-box { color: #1a1a1a !important; }
</style>
""", unsafe_allow_html=True)

st.title("Solar Plant Anomaly Detection Dashboard")

with st.spinner("Loading and merging data..."):
    df = load_and_merge()

with st.spinner("Running analysis pipeline..."):
    (
        daily_ac, fleet_avg, peak_hours,
        inverter_performance, anomalies_by_inverter,
        anomalies_by_day, scorecard,
    ) = run_analysis(df)

# ── Summary stats ─────────────────────────────────────────────────────────────
total_inverters  = df["INVERTER_KEY"].nunique()
critical_count   = int((scorecard["health_label"] == "Critical").sum())
warning_count    = int((scorecard["health_label"] == "Warning").sum())
healthy_count    = int((scorecard["health_label"] == "Healthy").sum())
worst_day        = str(anomalies_by_day.iloc[0]["day"]) if len(anomalies_by_day) else "N/A"
worst_day_count  = int(anomalies_by_day.iloc[0]["anomaly_count"]) if len(anomalies_by_day) else 0
fleet_avg_health = scorecard["health_score"].mean()
critical_df      = scorecard[scorecard["health_label"] == "Critical"].reset_index(drop=True)
warning_df       = scorecard[scorecard["health_label"] == "Warning"].reset_index(drop=True)

# ── Chart style helper ────────────────────────────────────────────────────────
def style_ax(ax, title="", xlabel="", ylabel=""):
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.yaxis.grid(True, alpha=0.3, linestyle="--")
    ax.tick_params(axis="both", labelsize=9)
    ax.set_facecolor("white")
    if title:  ax.set_title(title, fontsize=13)
    if xlabel: ax.set_xlabel(xlabel, fontsize=11)
    if ylabel: ax.set_ylabel(ylabel, fontsize=11)

# ── Single Groq call helper ───────────────────────────────────────────────────
def get_single_groq_rec(prompt: str) -> str:
    client = Groq(api_key=st.secrets["GROQ_API_KEY"])
    resp = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[{"role": "user", "content": prompt}],
    )
    return resp.choices[0].message.content

# ── HTML inverter table helper ────────────────────────────────────────────────
def build_inverter_table(df_critical: pd.DataFrame, df_warning: pd.DataFrame) -> str:
    rows = ""
    for _, row in df_critical.iterrows():
        rows += (
            f'<tr style="background:#fef2f2;color:#1a1a1a;">'
            f'<td style="padding:10px 14px;font-size:13px;">{row["INVERTER_KEY"]}</td>'
            f'<td style="padding:10px 14px;font-size:13px;color:#DC2626;font-weight:600;">Critical</td>'
            f'<td style="padding:10px 14px;font-size:13px;">{int(row["anomaly_count"])}</td>'
            f'<td style="padding:10px 14px;font-size:13px;">{row["avg_pct_deviation"]:.2f}%</td>'
            f'<td style="padding:10px 14px;font-size:13px;">{row["worst_z_score"]:.2f}</td>'
            f'<td style="padding:10px 14px;font-size:13px;">{row["health_score"]:.3f}</td>'
            f'</tr>'
        )
    for _, row in df_warning.iterrows():
        rows += (
            f'<tr style="background:#fff7ed;color:#1a1a1a;">'
            f'<td style="padding:10px 14px;font-size:13px;">{row["INVERTER_KEY"]}</td>'
            f'<td style="padding:10px 14px;font-size:13px;color:#D97706;font-weight:600;">Warning</td>'
            f'<td style="padding:10px 14px;font-size:13px;">{int(row["anomaly_count"])}</td>'
            f'<td style="padding:10px 14px;font-size:13px;">{row["avg_pct_deviation"]:.2f}%</td>'
            f'<td style="padding:10px 14px;font-size:13px;">{row["worst_z_score"]:.2f}</td>'
            f'<td style="padding:10px 14px;font-size:13px;">{row["health_score"]:.3f}</td>'
            f'</tr>'
        )
    return (
        '<table style="width:100%;border-collapse:collapse;border:1px solid #e5e7eb;'
        'border-radius:8px;overflow:hidden;">'
        '<thead>'
        '<tr style="background:#1e3a5f;color:white;font-weight:600;">'
        '<th style="padding:10px 14px;text-align:left;font-size:13px;">Inverter ID</th>'
        '<th style="padding:10px 14px;text-align:left;font-size:13px;">Status</th>'
        '<th style="padding:10px 14px;text-align:left;font-size:13px;">Anomaly Days</th>'
        '<th style="padding:10px 14px;text-align:left;font-size:13px;">Avg Deviation</th>'
        '<th style="padding:10px 14px;text-align:left;font-size:13px;">Worst Z-Score</th>'
        '<th style="padding:10px 14px;text-align:left;font-size:13px;">Health Score</th>'
        '</tr>'
        '</thead>'
        f'<tbody>{rows}</tbody>'
        '</table>'
    )

# ── Tabs ──────────────────────────────────────────────────────────────────────
tab1, tab2, tab3, tab4 = st.tabs([
    "Data Exploration", "Anomaly Detection", "Health Scorecard", "AI Recommendations",
])

# ════════════════════════════════════════════════════════════════════════════
# TAB 1 — Data Exploration
# ════════════════════════════════════════════════════════════════════════════
with tab1:
    st.markdown(
        "**Step 1 — Load & Clean**\n\n"
        "Four CSV files were loaded: two generation files (inverter-level DC/AC power and yield) "
        "and two weather sensor files (temperature and irradiation). The key challenge was datetime "
        "parsing — Plant 1 generation data used a non-standard day-first format (`%d-%m-%Y %H:%M`) "
        "requiring explicit format specification. `SOURCE_KEY` was renamed to `INVERTER_KEY` and "
        "`WEATHER_KEY` before merging on both `DATE_TIME` and `PLANT_ID`. The result: 136,472 rows, "
        "13 columns, no nulls, 44 inverters across 2 plants."
    )

    daily_total = daily_ac.groupby("day")["total_ac_power"].sum().reset_index()
    daily_total["day_dt"] = pd.to_datetime(daily_total["day"])
    daily_total = daily_total.sort_values("day_dt")

    fig, ax = plt.subplots(figsize=(13, 4), facecolor="white")
    ax.plot(daily_total["day_dt"], daily_total["total_ac_power"], color="#2563EB", linewidth=1.8)
    ax.fill_between(daily_total["day_dt"], daily_total["total_ac_power"], alpha=0.15, color="#2563EB")
    style_ax(
        ax,
        title="Fleet Daily Total AC Power — May 15 to June 17 2020",
        xlabel="Date",
        ylabel="Total AC Power (kWh)",
    )
    plt.xticks(rotation=45, ha="right")
    fig.tight_layout()
    st.pyplot(fig)
    plt.close(fig)
    st.caption(
        "Total AC output across all 44 inverters. "
        "Dips correspond to low-irradiation days (cloud cover or rain) "
        "rather than device faults."
    )
    st.caption(
        "No strong trend over 34 days — output oscillates between ~0.8M and ~1.3M. "
        "Dips around May 20, May 29, June 1, and June 11-12 likely correspond to "
        "low-irradiation weather days rather than device faults. No systematic degradation "
        "suggests both plants are operating normally overall."
    )

    st.markdown("<br>", unsafe_allow_html=True)
    st.markdown(
        "**Step 2 — EDA**\n\n"
        "Daily AC power per inverter was computed using a multi-index groupby on `day` and "
        "`INVERTER_KEY` with `reset_index()` to produce a clean flat DataFrame. Peak production "
        "hours were identified by averaging `AC_POWER` grouped by hour — confirming a bell curve "
        "peaking at hours 11-12. Chronic underperformers were identified by computing each "
        "inverter's average daily deviation from the fleet mean across all 34 days."
    )
    col_left, col_right = st.columns(2)

    with col_left:
        fig2, ax2 = plt.subplots(figsize=(6, 4), facecolor="white")
        ax2.bar(peak_hours["hour"], peak_hours["avg_ac_power"], color="#2563EB", edgecolor="none", alpha=0.85)
        style_ax(ax2, title="Peak Production Hours", xlabel="Hour of Day", ylabel="Avg AC Power (kW)")
        ax2.set_xticks(range(0, 24, 2))
        fig2.tight_layout()
        st.pyplot(fig2)
        plt.close(fig2)
        st.caption(
            "Production follows a solar bell curve peaking at hours 11-12. "
            "Zero output outside 6am-7pm confirms clean datetime parsing."
        )
        st.caption(
            "Production follows a solar bell curve peaking at hours 11-12 — this is the baseline "
            "normal behavior. Any inverter deviating significantly from this pattern within peak "
            "hours is a candidate for anomaly detection."
        )

    with col_right:
        bottom10 = inverter_performance.head(10).sort_values("avg_pct_deviation", ascending=True).copy()
        fig3, ax3 = plt.subplots(figsize=(6, 4), facecolor="white")
        ax3.barh(bottom10["INVERTER_KEY"], bottom10["avg_pct_deviation"], color="#DC2626", edgecolor="none", height=0.6)
        ax3.axvline(0, color="#6B7280", linewidth=0.8)
        style_ax(ax3, title="Top 10 Underperformers", xlabel="Avg % Deviation", ylabel="")
        ax3.tick_params(axis="y", labelsize=8)
        fig3.tight_layout()
        st.pyplot(fig3)
        plt.close(fig3)
        st.caption(
            "Inverters ranked by average daily deviation from fleet mean. "
            "Chronic underperformance suggests panel degradation or shading issues."
        )
        st.caption(
            "Chronic underperformance and sudden anomalies are different failure modes. "
            "This chart catches inverters consistently below fleet average across all 34 days. "
            "Sudden short-term deviations are caught in the Anomaly Detection tab using rolling z-scores."
        )


# ════════════════════════════════════════════════════════════════════════════
# TAB 2 — Anomaly Detection
# ════════════════════════════════════════════════════════════════════════════
with tab2:
    st.markdown(
        "**Step 3 — Anomaly Detection**\n\n"
        "A rolling z-score was computed per inverter using a 3-day window with `.shift(1)` — "
        "each reading is compared against the *previous* window, not its own, to avoid data leakage. "
        "Readings with absolute z-score > 2 are flagged as anomalies. This directly mirrors "
        "Avathon's Normal Behavior Modeling approach."
    )

    total_anomaly_flags = int(anomalies_by_inverter["anomaly_count"].sum())
    most_anomalous_inv  = anomalies_by_inverter.iloc[0]["INVERTER_KEY"] if len(anomalies_by_inverter) else "N/A"
    total_inverter_days = len(daily_ac)
    fleet_anomaly_rate  = total_anomaly_flags / total_inverter_days * 100 if total_inverter_days else 0

    a1, a2, a3, a4 = st.columns(4)
    a1.metric("Total Anomaly Flags",     total_anomaly_flags)
    a2.metric("Worst Day",               worst_day)
    a3.metric("Most Anomalous Inverter", most_anomalous_inv)
    a4.metric("Fleet Anomaly Rate",      f"{fleet_anomaly_rate:.2f}%")
    st.caption(
        "A z-score anomaly is flagged when a reading deviates more than 2 standard deviations "
        "from its own 3-day rolling average. Fleet-wide anomaly days likely indicate weather "
        "events rather than device faults."
    )
    st.caption(
        "333 total anomaly flags across 44 inverters over 34 days. June 13 had 37 out of 44 "
        "inverters flagged simultaneously — consistent with a fleet-wide weather event rather "
        "than individual device faults."
    )

    st.markdown("<br>", unsafe_allow_html=True)
    col_a, col_b = st.columns(2)

    with col_a:
        top10_inv = anomalies_by_inverter.head(10).sort_values("anomaly_count", ascending=True)
        fig4, ax4 = plt.subplots(figsize=(6, 4), facecolor="white")
        ax4.barh(top10_inv["INVERTER_KEY"], top10_inv["anomaly_count"], color="#DC2626", edgecolor="none", height=0.6, alpha=0.85)
        style_ax(ax4, title="Top 10 Most Anomalous Inverters", xlabel="Anomaly Count", ylabel="")
        ax4.tick_params(axis="y", labelsize=8)
        fig4.tight_layout()
        st.pyplot(fig4)
        plt.close(fig4)

    with col_b:
        top10_day = anomalies_by_day.head(10).sort_values("anomaly_count", ascending=True).copy()
        top10_day["day_str"] = top10_day["day"].astype(str)
        fig5, ax5 = plt.subplots(figsize=(6, 4), facecolor="white")
        ax5.barh(top10_day["day_str"], top10_day["anomaly_count"], color="#D97706", edgecolor="none", height=0.6, alpha=0.85)
        style_ax(ax5, title="Top 10 Most Anomalous Days", xlabel="Anomaly Count", ylabel="")
        ax5.tick_params(axis="y", labelsize=8)
        fig5.tight_layout()
        st.pyplot(fig5)
        plt.close(fig5)

    st.caption(
        "June 13 had 37 out of 44 inverters flagged simultaneously — consistent with a weather event. "
        "Device-level faults show as persistent anomalies across normal-weather days."
    )
    st.caption(
        "Device-level faults appear as persistent anomalies on days when the rest of the fleet is normal. "
        "Fleet-wide anomaly days (like June 13) should be filtered out before dispatching maintenance crews."
    )


# ════════════════════════════════════════════════════════════════════════════
# TAB 3 — Health Scorecard
# ════════════════════════════════════════════════════════════════════════════
with tab3:
    st.markdown(
        "**Step 4 — Device Health Scorecard**\n\n"
        "A composite health score combines three metrics normalized to 0-1: anomaly count "
        "(weight 0.35), average fleet deviation (weight 0.25), and worst single-day z-score "
        "(weight 0.40). Severity is weighted most heavily because a single catastrophic event "
        "warrants immediate inspection regardless of overall performance. Thresholds: "
        "Critical ≥ 0.5, Warning ≥ 0.35, Healthy below that."
    )

    h1, h2, h3, h4 = st.columns(4)
    h1.metric("Total Inverters", total_inverters)
    h2.metric("Critical",        critical_count)
    h3.metric("Warning",         warning_count)
    h4.metric("Healthy",         healthy_count)
    st.caption(
        "Health score combines anomaly frequency (35%), average fleet deviation (25%), "
        "and worst single-day z-score (40%). Higher weight on severity reflects "
        "industrial monitoring best practice."
    )

    st.markdown("<br>", unsafe_allow_html=True)

    sc_plot    = scorecard.sort_values("health_score", ascending=True)
    color_map  = {"Critical": "#DC2626", "Warning": "#D97706", "Healthy": "#059669"}
    bar_colors = sc_plot["health_label"].map(color_map).tolist()
    n          = len(sc_plot)

    fig6, ax6 = plt.subplots(figsize=(13, max(5, n * 0.28)), facecolor="white")
    ax6.barh(range(n), sc_plot["health_score"], color=bar_colors, edgecolor="none", height=0.7)
    ax6.set_yticks(range(n))
    ax6.set_yticklabels(sc_plot["INVERTER_KEY"], fontsize=7)
    ax6.axvline(0.50, color="#DC2626", linestyle="--", linewidth=1.2, alpha=0.85)
    ax6.axvline(0.35, color="#D97706", linestyle="--", linewidth=1.2, alpha=0.85)
    ax6.text(0.51, n - 1, "Critical (0.50)", color="#DC2626", fontsize=7.5, va="top")
    ax6.text(0.36, n - 1, "Warning (0.35)",  color="#D97706", fontsize=7.5, va="top")
    patches = [mpatches.Patch(color=c, label=l) for l, c in color_map.items()]
    ax6.legend(handles=patches, loc="lower right", fontsize=8)
    ax6.set_xlim(0, 1.12)
    style_ax(ax6, title="Inverter Health Scores", xlabel="Health Score", ylabel="")
    fig6.tight_layout()
    st.pyplot(fig6)
    plt.close(fig6)
    st.caption(
        "3 Critical inverters require immediate inspection. 7 Warning inverters should be monitored. "
        "The most critical inverter (rrq4fwE8jgrTyWY) scored 0.83 driven by a worst z-score of 109 — "
        "indicating a near-complete shutdown event on at least one day."
    )

    st.markdown("<br>", unsafe_allow_html=True)

    if len(critical_df) == 0:
        st.success("No critical inverters detected. Fleet is healthy.")
    else:
        most_critical = critical_df.iloc[0]
        crit_left, crit_right = st.columns([1, 2])

        with crit_left:
            st.markdown(
                f'<p style="font-size:14px;font-weight:600;margin:0 0 12px 0;">'
                f'Most Critical: <code>{most_critical["INVERTER_KEY"]}</code></p>',
                unsafe_allow_html=True,
            )
            mc1, mc2 = st.columns(2)
            mc1.metric("Anomaly Count",   int(most_critical["anomaly_count"]))
            mc2.metric("Health Score",    f"{most_critical['health_score']:.3f}")
            mc3, mc4 = st.columns(2)
            mc3.metric("Avg % Deviation", f"{most_critical['avg_pct_deviation']:.2f}%")
            mc4.metric("Worst Z-Score",   f"{most_critical['worst_z_score']:.2f}")

        with crit_right:
            critical_keys  = critical_df["INVERTER_KEY"].tolist()
            critical_daily = daily_ac[daily_ac["INVERTER_KEY"].isin(critical_keys)].copy()
            critical_daily["day_dt"] = pd.to_datetime(critical_daily["day"])
            fleet_plot = fleet_avg.copy()
            fleet_plot["day_dt"] = pd.to_datetime(fleet_plot["day"])

            fig8, ax8 = plt.subplots(figsize=(9, 4), facecolor="white")
            palette = plt.cm.Reds(np.linspace(0.4, 0.9, max(len(critical_keys), 1)))

            for i, key in enumerate(critical_keys):
                sub = critical_daily[critical_daily["INVERTER_KEY"] == key].sort_values("day_dt")
                ax8.plot(sub["day_dt"], sub["total_ac_power"], label=key, color=palette[i], linewidth=1.2, alpha=0.85)

            fleet_s = fleet_plot.sort_values("day_dt")
            ax8.plot(
                fleet_s["day_dt"], fleet_s["fleet_avg_power"],
                label="Fleet Average", color="black", linewidth=2.5, linestyle="--",
            )
            style_ax(ax8, title="Critical Inverters vs Fleet Average", xlabel="Date", ylabel="Daily AC Power (kWh)")
            plt.xticks(rotation=45, ha="right", fontsize=8)
            ax8.legend(fontsize=7, bbox_to_anchor=(1.01, 1), loc="upper left")
            fig8.tight_layout()
            st.pyplot(fig8)
            plt.close(fig8)
            st.caption(
                "Critical inverters plotted against fleet average. Sustained deviation below "
                "the fleet line confirms chronic underperformance beyond weather effects."
            )
            st.caption(
                "Critical inverters plotted against fleet average. Sustained deviation below the "
                "fleet line confirms chronic underperformance beyond weather effects. Note that "
                "rrq4fwE8jgrTyWY (highest health risk score) shows the most erratic behavior."
            )


# ════════════════════════════════════════════════════════════════════════════
# TAB 4 — AI Recommendations
# ════════════════════════════════════════════════════════════════════════════
with tab4:

    # ── Section 1: Fleet Health Summary ──────────────────────────────────────
    st.markdown(
        '<h3 style="font-size:17px;font-weight:700;margin-bottom:4px;">Fleet Health Summary</h3>',
        unsafe_allow_html=True,
    )
    if st.button("Generate Fleet Health Summary", type="primary"):
        fleet_prompt = (
            "You are an industrial AI assistant for a solar power plant operator. "
            "Given this fleet summary, provide a 4-5 sentence executive summary of overall "
            "fleet health, highlight the worst day and explain whether it was likely a "
            "weather event or device fault (if 30+ out of 44 inverters anomalied on the same "
            "day it is likely weather), and identify the top concern for the operator.\n\n"
            "Fleet stats:\n"
            f"- Total inverters: {total_inverters}\n"
            f"- Critical inverters: {critical_count}\n"
            f"- Warning inverters: {warning_count}\n"
            f"- Healthy inverters: {healthy_count}\n"
            f"- Worst day: {worst_day} with {worst_day_count} inverters flagged out of 44\n"
            f"- Fleet average health score: {fleet_avg_health:.3f}\n"
            "- Date range: May 15 to June 17 2020"
        )
        with st.spinner("Calling Groq (llama-3.1-8b-instant)..."):
            try:
                st.session_state["fleet_summary"] = get_single_groq_rec(fleet_prompt)
            except Exception as e:
                st.error(f"Groq API error: {e}")

    st.caption("4-5 sentence executive summary of fleet health, worst day classification, and top operator concern.")

    if "fleet_summary" in st.session_state:
        st.info(st.session_state["fleet_summary"])

    st.divider()

    # ── Section 2: Critical & Warning Inverter Recommendations ───────────────
    st.markdown(
        '<h3 style="font-size:17px;font-weight:700;margin-bottom:4px;">Critical & Warning Inverters</h3>',
        unsafe_allow_html=True,
    )

    if len(critical_df) > 0 or len(warning_df) > 0:
        st.markdown(build_inverter_table(critical_df, warning_df), unsafe_allow_html=True)
        st.markdown("<br>", unsafe_allow_html=True)

        all_inv_ids  = list(critical_df["INVERTER_KEY"]) + list(warning_df["INVERTER_KEY"])
        selected_inv = st.selectbox("Select an inverter to view its recommendation:", all_inv_ids)

        if st.button("Generate All Recommendations", type="primary"):
            with st.spinner("Calling Groq for all Critical and Warning inverters..."):
                try:
                    crit_recs = get_groq_recommendations(critical_df) if len(critical_df) > 0 else {}
                    warn_recs: dict[str, str] = {}
                    for _, row in warning_df.iterrows():
                        inv_id = row["INVERTER_KEY"]
                        warn_prompt = (
                            "You are an industrial AI assistant. This inverter is flagged as Warning — "
                            "monitor but not urgent. Given: "
                            f"anomaly count {int(row['anomaly_count'])}, "
                            f"avg deviation {row['avg_pct_deviation']:.2f}%, "
                            f"worst z-score {row['worst_z_score']:.2f}, "
                            f"health score {row['health_score']:.3f}. "
                            "Provide a 2 sentence monitoring recommendation."
                        )
                        warn_recs[inv_id] = get_single_groq_rec(warn_prompt)
                    st.session_state["all_recommendations"] = {**crit_recs, **warn_recs}
                except Exception as e:
                    st.error(f"Groq API error: {e}")

        if "all_recommendations" in st.session_state and selected_inv:
            rec         = st.session_state["all_recommendations"].get(selected_inv, "_No recommendation generated._")
            is_critical = selected_inv in critical_df["INVERTER_KEY"].values
            box_style   = (
                "border-left:4px solid #DC2626;background:#fef2f2;padding:16px;border-radius:4px;color:#1a1a1a;"
                if is_critical else
                "border-left:4px solid #D97706;background:#fff7ed;padding:16px;border-radius:4px;color:#1a1a1a;"
            )
            st.markdown(
                f'<div class="rec-box" style="{box_style}"><strong>{selected_inv}</strong><br><br>{rec}</div>',
                unsafe_allow_html=True,
            )
    else:
        st.success("No Critical or Warning inverters. Fleet is healthy.")

